# Prometheus development configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # APISIX metrics
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']
    scrape_interval: 5s

  # etcd metrics
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
    scrape_interval: 10s
