# Prometheus配置文件

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'amazon-tracker'
    environment: 'development'

# 规则文件配置 (暂时禁用)
# rule_files:
#   - "alert_rules.yml"
#   - "recording_rules.yml"

# 抓取配置
scrape_configs:
  # Prometheus自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 用户服务
  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: 'http'

  # 核心服务 (实际运行在8003端口)
  - job_name: 'core-service'
    static_configs:
      - targets: ['host.docker.internal:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: 'http'

  # 爬虫服务 (实际运行在8002端口)
  - job_name: 'crawler-service'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/api/v1/monitoring/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: 'http'

  # APISIX网关指标
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']  # APISIX Prometheus导出端口
    metrics_path: '/apisix/prometheus/metrics'
    scrape_interval: 15s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

# 存储配置通过命令行参数设置
# --storage.tsdb.retention.time=30d --storage.tsdb.retention.size=10GB
