#
# Working APISIX Configuration - Based on Official Template
#

deployment:
  role: data_plane
  role_data_plane:
    config_provider: etcd

  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: "dev-admin-key-123"
        role: admin

apisix:
  node_listen: 9080
  enable_admin: true
  admin_listen:
    ip: 0.0.0.0
    port: 9180

plugins:
  - jwt-auth
  - cors
  - limit-req

nginx_config:
  error_log: "stderr"
  error_log_level: "warn"
