#
# Simple APISIX Configuration for Development
#

apisix:
  node_listen: 9080
  enable_admin: true
  admin_key:
    - name: "admin"
      key: "dev-admin-key-123"
      role: admin

deployment:
  admin:
    admin_key:
      - name: "admin"
        key: "dev-admin-key-123"
        role: admin
    enable_admin_cors: true
    admin_listen:
      ip: 0.0.0.0
      port: 9180

  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

plugins:
  - prometheus
  - cors
  - jwt-auth
  - key-auth
  - limit-req
  - proxy-rewrite
  - redirect
