---
etcd:
  host:
  - http://etcd:2379
  watch_timeout: 50
  startup_retry: 2
  prefix: /apisix
  timeout: 30
  tls:
    verify: true
nginx_config:
  stream:
    access_log_format: $remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received
      $session_time
    access_log_format_escape: default
    lua_shared_dict:
      tars-stream: 1m
      upstream-healthcheck-stream: 10m
      etcd-cluster-health-check-stream: 10m
      lrucache-lock-stream: 10m
      plugin-limit-conn-stream: 10m
      worker-events-stream: 10m
    enable_access_log: false
    access_log: logs/access_stream.log
  main_configuration_snippet: ''
  http_configuration_snippet: ''
  http_server_configuration_snippet: ''
  http_server_location_configuration_snippet: ''
  http_admin_configuration_snippet: ''
  error_log_level: warn
  worker_processes: auto
  enable_cpu_affinity: false
  worker_rlimit_nofile: 20480
  worker_shutdown_timeout: 240s
  max_pending_timers: 16384
  max_running_timers: 4096
  meta:
    lua_shared_dict:
      status-report: 1m
      prometheus-metrics: 15m
      standalone-config: 10m
  event:
    use: epoll
    multi_accept: 'on'
    worker_connections: 10620
    accept_mutex: 'off'
  http:
    proxy_ssl_server_name: true
    access_log_format: $remote_addr - $remote_user [$time_local] $http_host "$request"
      $status $body_bytes_sent $request_time "$http_referer" "$http_user_agent" $upstream_addr
      $upstream_status $upstream_response_time "$upstream_scheme://$upstream_host$upstream_uri"
    charset: utf-8
    access_log_format_escape: default
    variables_hash_max_size: 2048
    access_log_buffer: 16384
    lua_shared_dict:
      plugin-api-breaker: 10m
      discovery: 1m
      jwks: 1m
      introspection: 10m
      access-tokens: 1m
      tracing_buffer: 10m
      tars: 1m
      cas-auth: 10m
      ocsp-stapling: 10m
      mcp-session: 10m
      internal-status: 10m
      upstream-healthcheck: 10m
      worker-events: 10m
      lrucache-lock: 10m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      etcd-cluster-health-check: 10m
      plugin-ai-rate-limiting: 10m
      plugin-ai-rate-limiting-reset-header: 10m
      plugin-limit-conn: 10m
      plugin-limit-conn-redis-cluster-slot-lock: 1m
      plugin-limit-req-redis-cluster-slot-lock: 1m
      plugin-limit-req: 10m
      plugin-limit-count: 10m
      plugin-limit-count-redis-cluster-slot-lock: 1m
      ext-plugin: 1m
      prometheus-metrics: 10m
    keepalive_timeout: 60s
    send_timeout: 10s
    client_header_timeout: 60s
    client_body_timeout: 60s
    client_max_body_size: '0'
    upstream:
      keepalive: 320
      keepalive_requests: 1000
      keepalive_timeout: 60s
    underscores_in_headers: 'on'
    real_ip_header: X-Real-IP
    enable_access_log: true
    real_ip_recursive: 'off'
    real_ip_from:
    - 127.0.0.1
    - 'unix:'
    access_log: /dev/stdout
  stream_configuration_snippet: ''
  http_end_configuration_snippet: ''
  error_log: /dev/stderr
apisix:
  proxy_cache:
    cache_ttl: 10s
    zones:
    - cache_levels: '1:2'
      name: disk_cache_one
      memory_size: 50m
      disk_size: 1G
      disk_path: /tmp/disk_cache_one
  enable_resolv_search_opt: true
  enable_control: true
  disable_sync_configuration_during_start: false
  enable_dev_mode: true
  enable_reuseport: true
  enable_ipv6: false
  proxy_mode: http
  extra_lua_cpath: ''
  normalize_uri_like_servlet: false
  enable_http2: true
  control:
    ip: 0.0.0.0
    port: 9092
  data_encryption:
    enable_encrypt_fields: true
    keyring:
    - qeddd145sfvddff3
    - edd1c9f0985e76a2
  node_listen:
  - 9080
  - ssl: true
    port: 9443
    http2: true
  router:
    http: radixtree_host_uri
    ssl: radixtree_sni
  enable_server_tokens: false
  events:
    module: lua-resty-events
  resolver_timeout: 5
  ssl:
    ssl_trusted_certificate: /etc/ssl/certs/ca-certificates.crt
    enable: true
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl_session_tickets: false
    ssl_protocols: TLSv1.2 TLSv1.3
    listen:
    - enable_http3: false
      port: 9443
  extra_lua_path: ''
  show_upstream_status_in_response_header: false
  enable_admin: true
  delete_uri_tail_slash: false
  admin_key:
  - key: dev-admin-key-123
    role: admin
    name: admin
  - key: dev-viewer-key-456
    role: viewer
    name: viewer
graphql:
  max_size: 1048576
wasm:
  plugins:
  - http_request_phase: access
    priority: 7999
    file: /opt/apisix/wasm/wasm_log.wasm
    name: wasm_log
deployment:
  admin:
    admin_listen:
      ip: 0.0.0.0
      port: 9180
    enable_admin_cors: true
    admin_key_required: true
    enable_admin_ui: true
    allow_admin:
    - 127.0.0.0/24
    - 0.0.0.0/0
    admin_api_version: v3
    admin_key:
    - key: mOBBjnZDVLRTEgNkUsrFTjLZgCieEGer
      role: admin
      name: admin
  etcd:
    host:
    - http://etcd:2379
    watch_timeout: 50
    startup_retry: 2
    prefix: /apisix
    timeout: 30
    tls:
      verify: true
  role: traditional
  role_traditional:
    config_provider: etcd
  config_provider: etcd
stream_plugins:
- mqtt-proxy
- ip-restriction
- limit-conn
plugin_attr:
  zipkin:
    set_ngx_var: false
  server-info:
    report_ttl: 60
  inspect:
    delay: 3
    hooks_file: /usr/local/apisix/plugin_inspect_hooks.lua
  dubbo-proxy:
    upstream_multiplex_count: 32
  opentelemetry:
    trace_id_source: x-request-id
    set_ngx_var: false
    resource:
      service.version: 1.0.0
      service.name: APISIX-Gateway
    collector:
      request_timeout: 3
      request_headers:
        Authorization: token
        Content-Type: application/x-protobuf
      address: jaeger:4318
    batch_span_processor:
      inactive_timeout: 1
      max_export_batch_size: 16
      drop_on_queue_full: false
      max_queue_size: 1024
      batch_timeout: 2
  prometheus:
    export_uri: /apisix/prometheus/metrics
    export_addr:
      ip: 0.0.0.0
      port: 9091
    metric_prefix: apisix_
    enable_export_server: true
  skywalking:
    service_name: APISIX
    report_interval: 3
    endpoint_addr: http://127.0.0.1:12800
    service_instance_name: APISIX Instance Name
  proxy-mirror:
    timeout:
      read: 60s
      send: 60s
      connect: 60s
  log-rotate:
    interval: 3600
    max_kept: 168
    enable_compression: false
    max_size: -1
    timeout: 10000
plugins:
- real-ip
- ai
- client-control
- proxy-control
- request-id
- zipkin
- opentelemetry
- prometheus
- node-status
- jwt-auth
- key-auth
- basic-auth
- authz-keycloak
- wolf-rbac
- ldap-auth
- hmac-auth
- authz-casbin
- authz-casdoor
- consumer-restriction
- cors
- uri-blocker
- ip-restriction
- ua-restriction
- referer-restriction
- csrf
- proxy-rewrite
- redirect
- response-rewrite
- fault-injection
- mocking
- serverless-pre-function
- serverless-post-function
- ext-plugin-pre-req
- ext-plugin-post-req
- limit-req
- limit-conn
- limit-count
- proxy-cache
- request-validation
- openid-connect
- proxy-mirror
- api-breaker
- traffic-split
- request-id
- proxy-control
- client-control
- gzip
- server-info
- dubbo-proxy
- mqtt-proxy
...
