#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# APISIX Standard Configuration for Development

apisix:
  # Node listening configuration
  node_listen: 9080                # HTTP port
  enable_heartbeat: true
  enable_admin: true
  enable_admin_cors: true
  enable_debug: false
  
  # Development mode
  enable_dev_mode: false
  enable_reuseport: true
  enable_ipv6: false

  # Admin configuration
  admin_key:
    - name: "admin"
      key: "dev-admin-key-123"
      role: admin
    - name: "viewer"  
      key: "dev-viewer-key-456"
      role: viewer

  # Admin API listening
  admin_listen:
    ip: 0.0.0.0
    port: 9180

  # HTTPS configuration (for future use)
  ssl:
    enable: false
    listen: 9443
    ssl_protocols: "TLSv1.2 TLSv1.3"
    
  # Disable unwanted features
  enable_control: false
  control:
    ip: "127.0.0.1"
    port: 9092

# Configuration deployment
deployment:
  role: data_plane
  role_data_plane:
    config_provider: etcd

  # etcd configuration
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30
    startup_retry: 2
    health_check_retry: 2
    user: ""
    password: ""
    tls:
      verify: false

  # Admin configuration  
  admin:
    admin_key:
      - name: "admin"
        key: "dev-admin-key-123"
        role: admin

    enable_admin_cors: true
    allow_admin:
      - 127.0.0.1/24
      - 172.0.0.0/8
      - 10.0.0.0/8
      - 0.0.0.0/0  # Allow all for development
    
    admin_listen:
      ip: 0.0.0.0
      port: 9180

    https_admin: false

# Plugin configuration
plugins:
  - real-ip
  - ai
  - client-control
  - proxy-control
  - request-id
  - zipkin
  - ext-plugin-pre-req
  - ext-plugin-post-req
  - fault-injection
  - mocking
  - serverless-pre-function
  - serverless-post-function
  - cors
  - ip-restriction
  - ua-restriction
  - referer-restriction
  - csrf
  - uri-blocker
  - request-validation
  - openid-connect
  - authz-casbin
  - authz-casdoor
  - wolf-rbac
  - ldap-auth
  - hmac-auth
  - basic-auth
  - jwt-auth
  - key-auth
  - consumer-restriction
  - authz-keycloak
  - opa
  - forward-auth
  - oas-validation
  - limit-req
  - limit-conn
  - limit-count
  - proxy-cache
  - request-id
  - proxy-mirror
  - api-breaker
  - traffic-split
  - request-validation
  - prometheus
  - node-status
  - redirect
  - response-rewrite
  - proxy-rewrite
  - grpc-transcode
  - grpc-web
  - public-api
  - gzip
  - server-info
  - dubbo-proxy

# Stream proxy plugins
stream_plugins:
  - mqtt-proxy
  - ip-restriction
  - limit-conn
  - prometheus

# xRPC plugins  
xrpc:
  protocols:
    - name: redis

# nginx configuration
nginx_config:
  # Error log configuration
  error_log: "/dev/stderr"
  error_log_level: "warn"
  
  # Worker configuration
  worker_processes: "auto"
  enable_cpu_affinity: false
  worker_rlimit_nofile: 20480
  worker_shutdown_timeout: "240s"

  # Event configuration
  event:
    worker_connections: 10620
    use: epoll
    multi_accept: "on"
    accept_mutex: "off"

  # HTTP configuration
  http:
    access_log: "/dev/stdout"
    keepalive_timeout: "60s"
    client_header_timeout: "60s"
    client_body_timeout: "60s"
    client_max_body_size: "0"
    send_timeout: "10s"
    underscores_in_headers: "on"
    real_ip_header: "X-Real-IP"
    real_ip_from:
      - 127.0.0.1
      - "unix:"

    # Lua configuration
    lua_shared_dict:
      internal-status: 10m
      plugin-limit-req: 10m
      plugin-limit-count: 10m
      plugin-limit-conn: 10m
      plugin-limit-count-redis-cluster-slot-lock: 1m
      worker-events: 10m
      lrucache-lock: 10m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      plugin-limit-count-redis-cluster-slot-lock: 1m
      tracing_buffer: 10m
      plugin-api-breaker: 10m
      etcd-cluster-health-check: 10m
      discovery: 1m
      jwks: 1m
      introspection: 10m
      access-tokens: 1m
      ext-plugin: 1m

# Discovery configuration (completely disable consul)
discovery: {}

# Wasm configuration (optional)
wasm:
  plugins: []

# Plugin metadata
plugin_metadata:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091