apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  database-url: "postgresql://user:password@postgres:5432/amazon_tracker"
  redis-url: "redis://redis:6379/0"
  jwt-secret-key: "your-jwt-secret-key-here"
  openai-api-key: "your-openai-api-key-here"
  apify-api-token: "your-apify-api-token-here"