apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    service: user-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  selector:
    service: core-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  selector:
    service: crawler-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
spec:
  selector:
    app: apisix
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    name: http
  - protocol: TCP
    port: 9443
    targetPort: 9443
    name: https
  type: LoadBalancer